### ISSUE TITLE
This plug-in has never been used successfully

### ISSUE THREAD

**Issue by wo2350405615** [RLoris/SocketHelperDoc#3]
Can you give a tutorial to teach users how to use this plug-in correctly, because so far I have never successfully used this plug-in for TCP or UDP communication.Although I have read all the documents, it is too difficult to work with this plug-in. I once used an objectdeliverer plug-in, which produced good documents and cases

**Comment by RLoris** [comment]
What do you want to create a client / server ? If you understand how TCP and UDP works, this plugin is only one node use (open the connection and receive the events), I can improve the documentation but you have to tell me what you do not understand, I suggest you first understand how these transport protocol works, then it's really easy to use !

**Comment by RLoris** [comment]
I will add example for TCP client and TCP server and UDP in the documentation !

**Comment by RLoris** [comment]
Hello again @wo2350405615, I have updated the documentation with live blueprint example ! Check them out, it's pretty straightforward if you understand these exchange protocols
