### ISSUE TITLE
Release for Unreal v 5.1

### ISSUE THREAD

**Issue by vwc262** [RLoris/SocketHelperDoc#5]
Hi there, just wanna know if there's any chance of making a release for Unreal v 5.1.

I will really appreciate it.
Thank you in advance.

**Comment by RLoris** [comment]
Hello there, yes I'm planning on doing so, I have updated all my plugins, this is the last one, I wanted to improve a few things, I only work during weekend on my plugins, + epic takes a lot of time to review files and approve them (sometimes a week) ... Stay tuned, will try to submit this last one as soon as possible.

**Comment by vwc262** [comment]
Great to hear that. Thank you very much. I am looking forward to seeing the release. 😄

**Comment by RLoris** [comment]
@vwc262 Happy new year, just wanted to tell you that plugin files have been submitted to the marketplace, now we only need to wait for epic to approve it, after that the update for 5.1 will be available to everyone.
